---
title: "Vis_2"
output: github_document
date: "2024-10-01"
---

```{r setup, include=FALSE}
library(tidyverse)
```

Import the weather data. 
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

Making our first plot :-) 

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```


```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + 
  labs(
    title = "Temperture scatterplot", 
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    color = "Location", 
    caption = "Weather data taken from the rnoaa package from three stations."
  )
```

Scales == start with 'x' and 'y' and then do 'color'. 

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + 
  labs(
    title = "Temperture scatterplot", 
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    color = "Location", 
    caption = "Weather data taken from the rnoaa package from three stations."
  ) + 
  scale_x_continuous(
    breaks = c(-15,0,20), 
    labels = c("-15", "0", "20") 
  ) + 
  scale_y_continuous(
    limits = c (0,30), 
    transform = "sqrt"
  )
```

Look at the color: 
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + 
  labs(
    title = "Temperture scatterplot", 
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    color = "Location", 
    caption = "Weather data taken from the rnoaa package from three stations."
  ) + 
  scale_color_hue(h = c(100,400)) + 
  viridis::scale_color_viridis(discrete = TRUE)
```

## Themes 
```{r}
gg_scatterplot = 
  weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + 
  labs(
    title = "Temperture scatterplot", 
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    color = "Location", 
    caption = "Weather data taken from the rnoaa package from three stations."
  ) + 
  scale_color_hue(h = c(100,400)) + 
  viridis::scale_color_viridis(discrete = TRUE)
```

```{r}
gg_scatterplot + 
  theme(legend.position = "bottom")
```
```{r}
gg_scatterplot + 
  theme_bw() +
  theme(legend.position = "bottom")
```
```{r}
gg_scatterplot + 
  theme(legend.position = "bottom") + 
  theme_classic()
```

```{r}
gg_scatterplot + 
  theme(legend.position = "bottom") + 
  ggthemes
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3)

gg_tmax_density = 
  weather_df |>
  ggplot(aes(x=tmax, fill = name)) + 
  geom_density(alpha = .3)
```

## Data manipulation 

```{r}
weather_df |>
  mutate(name = fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))) |>
  ggplot(aes(x = name, y = tmax, fill = name)) + 
  geom_violin(alpha = 0.5)
```

PULSE data next. 

```{r}

```

